name: Conexión a S3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código de frontend
      uses: actions/checkout@v2

    - name: Configuración de acceso AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2

    - name: Instalación de Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
  
    - name: Instalación de independencias
      run: npm install

    - name: Build de Vite
      run: npm run build

    - name: Copia de archivos a Amazon S3
      run: |
        aws s3 sync . s3://1023c07-grupo5/ --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
